name: app_analisis_mecanico
description: A new Flutter project.

# Versión de Dart y Flutter necesarias para el proyecto
environment:
  sdk: '^3.5.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.17.0

dependency_overrides:
  async: ^2.12.0
  boolean_selector: ^2.1.2
  characters: ^1.3.1
  clock: ^1.1.2
  collection: ^1.19.1
  fake_async: ^1.3.2
  http_parser: ^4.1.1
  leak_tracker: ^10.0.8
  leak_tracker_flutter_testing: ^3.0.9
  matcher: ^0.12.17
  material_color_utilities: ^0.12.0
  meta: ^1.16.0
  path: ^1.9.1
  stack_trace: ^1.12.0
  string_scanner: ^1.4.0
  test_api: ^0.7.3
  vm_service: ^14.3.1
  lints: ^5.1.0

flutter:
  uses-material-design: true
